#9 Issue/9 追加テーブルの設計
matsushun-58/lamp_practice pull request #10
Opened 2020-04-13 11:38 UTC by matsushun-58

「購入履歴画面」「購入詳細画面」を表示するために、lamp_dockディレクトリに新たにappend_schema.sqlを作成しました。
内容を確認していただき、マージをお願いいたします。

2020-04-15 00:20 UTC, thisprodigiousgeek requested changes
ほぼ完成していますね！あとは両テーブルともON UPDATEの設定をupdatedカラムの方に変更して、スペルミスに気をつけておきましょう。

2020-04-15 00:20 UTC, thisprodigiousgeek commented on lamp_dock/append_schema.sql
> +  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAM,
行末のPが抜けているようです！

2020-04-15 00:20 UTC, thisprodigiousgeek commented on lamp_dock/append_schema.sql
> +  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAM,
また、ON UPDATEを設定するのはcreatedではなくupdatedのカラムですね！

2020-04-16 04:26 UTC, matsushun-58 commented
ON UPDATEの位置修正を行いました。ご指摘ありがとうございました。
又、スペルミス失礼いたしました。こちらで再度確認していただき、マージをお願いいたします。

2020-04-16 09:56 UTC, thisprodigiousgeek approved these changes
はい、こちらでバッチリですね！マージさせていただきます！

2020-04-16 09:58 UTC, merged