関数hをfunction.phpに追記
matsushun-58/lamp_practice pull request #2
Opened 2020-03-23 14:29 UTC by matsushun-58

function.phpに関数hを追記しましたので、マージをお願いいたします。

2020-03-25 14:24 UTC, thisprodigiousgeek requested changes
エスケープ用関数の実装、しっかり行われていらっしゃいますね！
引数名に少し問題があったので、修正してみましょう！

2020-03-25 14:24 UTC, thisprodigiousgeek commented on www/model/functions.php
> +function h($s) {
$s は引数名としてわかりにくいですね！文字列を受け取ることが想像しやすい引数名に変更しましょう！

2020-03-26 11:45 UTC, matsushun-58 commented on www/model/functions.php
> +function h($s) {
関数名を$s → $escapeに変更しました。こちらでどうでしょうか?

2020-03-26 12:19 UTC, thisprodigiousgeek approved these changes
わかりやすい引数名になりましたね！こちらでOKです。
マージさせていただきます！

2020-03-26 12:19 UTC, merged