#3 SQLインジェクション対策として、プリペアードステートメントのバインドを利用しました
matsushun-58/lamp_practice pull request #7
Opened 2020-04-02 11:51 UTC by matsushun-58

modelディレクトリの
-  cart.php
-  item.php
-  user.php
の中の関数

- cart.php

- [ ] get_user_carts
- [ ]  get_user_cart
- [ ]  insert_cart
- [ ]  update_cart_amount
- [ ]  delete_cart
- [ ]  delete_user_carts

- item.php
- [ ]  get_item
※get_itemsは必要ないと判断してそのままにしました
- [ ]  insert_item
- [ ]  update_item_status
- [ ]  update_item_stock
- [ ]  delete_item

- user.php
- [ ]  get_user
- [ ]  get_user_by_name
- [ ]  insert_user

にバインド処理を行いました。マージをお願いします。

2020-04-03 09:56 UTC, thisprodigiousgeek requested changes
順調に書き換えが進んでいらっしゃいますね！
いくつかケアレスミスの箇所が見られました。
すぐにエラーが発生して気づけるミスばかりですので、コードを修正後実行して確認が行われていないものと思われます。
該当箇所を修正した上で、今回修正を行った全ての関数について動作確認を行ってから再度レビュー依頼をお願いいたします！

2020-04-03 09:56 UTC, thisprodigiousgeek commented on www/model/item.php
> +    ':price' => $name,
priceの箇所に$nameが入っていますね！修正しておきましょう。
また、こちらのミスは該当箇所を実行していればすぐに気づける箇所です。
コードの修正を行ったら、必ず該当箇所を実行して確認するようにしましょう！

2020-04-03 09:56 UTC, thisprodigiousgeek commented on www/model/item.php
> +    ':item/id' => $item_id
こちらもプレースホルダの綴りがおかしくなっていますね！

2020-04-03 09:56 UTC, thisprodigiousgeek commented on www/model/user.php
> +  return fetch_query($db, $sql, $name);
第三引数がおかしいですね！

2020-04-03 12:26 UTC, matsushun-58 commented
不十分な状態でプルリクエストを出してしまい、大変申し訳ございません。
指摘箇所に加えて他の関数も再度確認し、実行して修正作業を行いました。

恐れ入りますが、再度ご確認のほど、よろしくお願いいたします。

2020-04-04 08:37 UTC, thisprodigiousgeek approved these changes
こちらでバッチリ修正していただけましたね！素晴らしいです。
マージさせていただきます！

2020-04-04 08:37 UTC, merged