Issue/6 #6 CSRF対策の実装
matsushun-58/lamp_practice pull request #8
Opened 2020-04-07 19:27 UTC by matsushun-58

CSRF対策として

1. トークンの生成
- [ ] admin.php
- [ ] cart.php
- [ ] index.php
- [ ] login.php
- [ ] signup.php

2. トークンの埋め込み
- [ ] admin_view.php
- [ ] cart_view.php
- [ ] index_view.php
- [ ] login_view.php
- [ ] signup_view.php

3. トークンの照合
- [ ] admin_change_status.php
- [ ] admin_change_stock.php
- [ ] admin_delete_item.php
- [ ] admin_insert_item.php
- [ ] cart_change_amount.php
- [ ] cart_delete_cart.php
- [ ] finish.php
- [ ] index_add_cart.php
- [ ] login_process.php
- [ ] signup_process.php

上記のコードに実装し、検証しました。コードを確認していただき、マージをお願いいたします。

2020-04-08 15:15 UTC, thisprodigiousgeek requested changes
完成間近のところまで出来上がっていますね！素晴らしいです。
現在は$_POSTの値をそのまま使っていますが、現行のコードの他の箇所ではどのようにして$_POSTの値を取得しているでしょうか？他のコードをよく読んで、$_POSTの値の適切な利用方法を見つけてみましょう！

2020-04-09 14:49 UTC, matsushun-58 commented
change_amount.phpを参考にした際に、

`if(update_cart_amount($db, $cart_id, $amount)){ //カートの数量がアップデートされた場合
  set_message('購入数を更新しました。'); //メッセージ表示
} else {
  set_error('購入数の更新に失敗しました。'); //エラーメッセージ表示
}`

上記のように引数に「$_POST」ではなく変数「$db,$cart_id,$amount」を使用しているので、

`if (is_valid_csrf_token($_POST['csrf_token']) === false){
  set_error('不正なアクセスです。'); //エラーメッセージ表示
  redirect_to(HOME_URL);
}`

上記の$_POSTを$csrf_token(※cart.phpで設定した)に置き換えて、プルリクエストしたいと思います。

2020-04-10 16:00 UTC, matsushun-58 commented
- [ ]  admin_change_status.php
- [ ]  admin_change_stock.php
- [ ]  admin_delete_item.php
- [ ]  admin_insert_item.php
- [ ]  cart_change_amount.php
- [ ]  cart_delete_cart.php
- [ ]  finish.php
- [ ]  index_add_cart.php
- [ ]  login_process.php
- [ ]  signup_process.php

上記のコードを、変数$csrf_tokenを設定して修正しました。
確認していただき、マージをお願いいたします。

2020-04-15 21:25 UTC, thisprodigiousgeek requested changes
こちらまだ$_POSTの利用箇所が修正されていないようですがいかがですか？

2020-04-16 04:34 UTC, matsushun-58 commented
プッシュができておりませんでした。大変失礼いたしました。
お手数をおかけしますが、再度確認していただき、マージをお願いいたします。

2020-04-16 09:58 UTC, thisprodigiousgeek requested changes
こちらで$_POSTの問題は解決ですね！また、iframeの禁止はindex.phpにしかないようですが、こちらはpushできていらっしゃいますか？

2020-04-16 13:13 UTC, matsushun-58 commented
index.phpのみ処理実装していたiframeを利用したトークン盗難防止の処理を、

- [ ] admin.php
- [ ] cart.php
- [ ] finish.php
- [ ] index.php
- [ ] login.php

以上のファイルに追加しました。

2020-04-16 20:40 UTC, thisprodigiousgeek approved these changes
はい、こちらでバッチリですね！マージさせていただきます！

2020-04-16 20:40 UTC, merged